name: balamod
description: "A mod loader for the game Balatro"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.2.3
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  json_annotation: ^4.8.1
  flutter_native_splash: ^2.4.0
  hydrated_bloc: ^9.1.5
  archive: ^3.4.10
  equatable: ^2.0.5
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  win32_registry: ^1.1.2
  http: ^1.2.1
  tar: ^1.0.4
  github: ^9.24.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build: ^2.4.1
  build_runner: ^2.4.8
  source_gen: ^1.5.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/RobotoMono-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"